expression = 
    simple_expression, [ ( "=" | "<" | ">" | "<=" | ">=" ), simple_expression ]
;

simple_expression = 
    [ "+" | "-" ], term, { [ "+" | "-" ], term }
;

bracketed_expression = 
    "(", expression, ")"
;

term =
    factor, { ( "**" | "*" | "/" | % ), factor }
;

factor = 
    integer |
    dice_roll |
    function_call |
    bracketed_expression
;

function_call = 
    identifier, "(", expression, ")"
;

(* TODO: Compare points. 1d4>3f1 *)