expression = 
    simple_expression, [ boolean_operator, simple_expression ]
;

simple_expression = 
    [ "+" | "-" ], term, { [ "+" | "-" ], term }
;

term =
    factor, { ( "**" | "*" | "/" | % ), factor }
;

factor = 
    simple_factor |
    dice_roll |
    function_call |
    expression_group
;

simple_factor = 
    number |
    bracketed_expression
;

function_call = 
    identifier, "(", expression, ")"
;

bracketed_expression = 
    "(", expression, ")"
;

boolean_operator = 
    "=" | "<" | ">" | "<=" | ">="
;