export enum TokenType {
    BoolOpEq = <any>"=",
    BoolOpGreater = <any>">",
    BoolOpGreaterOrEq = <any>">=",
    BoolOpLess = <any>"<",
    BoolOpLessOrEq = <any>"<=",
    BraceClose = <any>"}",
    BraceOpen = <any>"{",
    Comma = <any>",",
    Identifier = <any>"identifier",
    MathOpAdd = <any>"+",
    MathOpDivide = <any>"/",
    MathOpExponent = <any>"**",
    MathOpModulo = <any>"%",
    MathOpMultiply = <any>"*",
    MathOpSubtract = <any>"-",
    NumberInteger = <any>"number",
    ParenthesisClose = <any>")",
    ParenthesisOpen = <any>"(",
    Terminator = <any>"terminator",
    UnOpExplode = <any>"!",
    UnOpPenetrate = <any>"!!"
}
